### ISSUE TITLE
Readme Instructions for Standalone Launch Incomplete

### ISSUE THREAD

**Issue by coreytodaro-da** [digital-asset/ex-healthcare-claims-processing#43]
The launch command for the standalone method is missing an option. 

`daml start --sandbox-option --address=localhost --sandbox-port 7600 `

Without the port option, the javabot cannot successfully load.

**Comment by richardkapolnai-da** [comment]
Thanks for reporting this issue. We accidentally removed this in several readmes. We will fix this urgently.
